schedules:
- cron: "30 06 * * *"
  displayName: Daily build
  branches:
    include:
      - master
  always: true

jobs:
  - job: debug
    timeoutInMinutes: 180
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - script: |
          df -h
          time sudo rm -rf /usr/share/dotnet
          df -h
          time sudo rm -rf /opt/ghc
          df -h
          time sudo rm -rf /usr/local/lib/android
          df -h
          time sudo rm -rf /var/cache/apt/archives
          df -h
          sudo du / -x -h > /tmp/sizes
          sort -h /tmp/sizes|tail -n100
        displayName: 'Debug disk space issue'


variables:
  - name: DOCKER_BUILDKIT
    value: '1'
  - name: DOCKER_CLI_EXPERIMENTAL
    value: enabled
  - name: DOCKER_COMMAND
    value: docker buildx build docker-definition
  - name: CACHE_KEY_BASE  # Increment this value to reset the images cache
    value: 21
  - name: CACHE_KEY_FILES
    value: $(System.DefaultWorkingDirectory)/docker-definition/*
  - name: CACHE_KEY_IMAGES
    value: BASE_SEED=$(CACHE_KEY_BASE) | $(CACHE_KEY_FILES)
  - name: CACHE_KEY_IMAGES_FALLBACK
    value: BASE_SEED=$(CACHE_KEY_BASE)
  - name: SENTINEL_CACHE_PATH
    value: $(Pipeline.Workspace)/sentinel_cache
  - name: IMAGE_CACHE_PATH
    value: $(Pipeline.Workspace)/image_cache
  - name: needs_build
    value: "false"
